app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});

Route::group(['middleware' => 'web'], function () {
    Route::auth();
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index');
    Route::resource('role', 'RoleController');
    Route::resource('permission', 'PermissionController');
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
     /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title','slug'];
    /*
     * relationships
     */
    public function users(){
        return $this->belongsToMany('App\Models\User')->withTimestamps();
    }
    public function permissions(){
        return $this->belongsToMany('App\Models\Permission')->withTimestamps();
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class RoleController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $this->authorize('index', new \App\Models\Role);
        return view('roles.index', ['roles' => \App\Models\Role::paginate(15)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $this->authorize('create', new \App\Models\Role);
        $list = \App\Models\Permission::lists('title', 'id');
        return view('roles.create', ['pList' => $list]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(\App\Http\Requests\StoreRolePostRequest $request) {
        $this->authorize('create', new \App\Models\Role);
        $role = \App\Models\Role::create($request->only(['title', 'slug']))->permissions()->sync($request->get('permissions'));
        return redirect(route('role.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $role = \App\Models\Role::findOrFail($id);
        $this->authorize('update', $role);
        $list = \App\Models\Permission::lists('title', 'id');
//        dd($role->permissions()->lists('id'));
        return view('roles.edit', ['pList' => $list, 'role' => $role]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(\App\Http\Requests\UpdateRolePostRequest $request, $id) {
        $role = \App\Models\Role::findOrFail($id);
        $this->authorize('update', $role);
        $role->fill($request->only(['title', 'slug']));
        $role->save();
        $role->permissions()->sync($request->get('permissions'));
        return redirect(route('role.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        $role = \App\Models\Role::findOrFail($id);
        $this->authorize('destroy', $role);
        $role->delete();
        return redirect(route('role.index'));
    }

}

resources/views/roles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Create New Role</div>
                <div class="panel-body">
                    @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <form method="POST" action="{{route('role.store')}}">
                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" class="form-control" id="title" placeholder="Title" name="title" value="{{ old('title') }}">
                        </div>
                        <div class="form-group">
                            <label for="slug">Slug</label>
                            <input type="text" class="form-control" id="slug" placeholder="Slug" name="slug" value="{{ old('slug') }}">
                        </div>
                        <div class="form-group">
                            <label for="permissions">Permissions</label>
                            <select multiple="true" id="permissions" name="permissions[]" class="form-control">
                                @foreach($pList as $key=>$val)
                                <option value="{{$key}}">{{$val}}</option>
                                @endforeach
                            </select>
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Create New Role</div>
                <div class="panel-body">
                    @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <form method="POST" action="{{route('role.update',['role'=>$role->id])}}">
                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                        <input type="hidden" name="_method" value="PUT">
                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" class="form-control" id="title" placeholder="Title" name="title" value="{{ $role->title }}">
                        </div>
                        <div class="form-group">
                            <label for="slug">Slug</label>
                            <input type="text" class="form-control" id="slug" placeholder="Slug" name="slug" value="{{ $role->slug }}" >
                        </div>
                        <div class="form-group">
                            <label for="permissions">Permissions</label>
                            <select multiple="true" id="permissions" name="permissions[]" class="form-control">
                                @foreach($pList as $key=>$val)
                                <option value="{{$key}}" @if(in_array($key,$role->permissions()->lists('id','id')->toArray())) selected @endif > 
                                        {{$val}} 
                            </option>
                            @endforeach
                        </select>
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Roles 
                    <a href="{{route('role.create')}}" class="pull-right">Add New</a>
                </div>

                <div class="panel-body">
                    <!--<div class="container">-->
                    
                    <table class="table table-striped">
                        <thead>
                        <th>Title</th>
                        <th>Slug</th>
                        <th>Action</th>
                        </thead>
                        <tbody>
                            @foreach ($roles as $role)
                            <tr>
                                <td>{{ $role->title }}</td>
                                <td>{{ $role->slug }}</td>
                                <td>
                                    <div class="btn-group col-md-12" > 
                                    <form method="POST" action="{{route('role.destroy',['role'=>$role->id])}}">
                                        <input type="hidden" value="DELETE" name="_method">
                                        <input type="hidden" value="{{csrf_token()}}" name="_token">
                                        <input type="submit" value="Delete" class="btn btn-danger pull-right">
                                    </form>    
                                    <form method="GET" action="{{route('role.edit',['role'=>$role->id])}}">
                                        <input type="submit" value="Edit" class="btn btn-primary pull-right">
                                    </form>
                                        
                                    
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                    <!--</div>-->

                    {!! $roles->links() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection